### ISSUE TITLE
rename repo to reflect new scope

### ISSUE THREAD

**Issue by PeerHerholz** [main-educational/brain_encoding_decoding#15]
Hi everyone,

I think it might be good to rename this repo to `brain_decoding` (or something comparable) to reflect the new scope of this session, ie removing the `encoding` part. WDYT? Tagging the admins/organizers @pbellec and @htwangtw (sorry if I missed anyone).

Cheers, Peer

**Comment by htwangtw** [comment]
That's fine by me. 

Unrelated - where is the encoding part hosted now?

**Comment by PeerHerholz** [comment]
Hi @htwangtw,

thx for the reply. 

>  Unrelated - where is the encoding part hosted now?

I think it will become its own `repo`/`jupyter-book`.

Cheers, Peer

**Comment by PeerHerholz** [comment]
Hi folks,

I think this needs to be reverted as I misunderstood something re the split of `decoding` and `encoding`: while the sessions are split (ie there's one session for `decoding` and one for `encoding`, happening in parallel), the materials are not.
I'm very sorry for this.

Best, Peer

**Comment by htwangtw** [comment]
@PeerHerholz I am giving you admin right so that's easier for you to coordinate things in this repo

**Comment by PeerHerholz** [comment]
Hi @htwangtw, thanks and sorry for the back and forth!

**Comment by htwangtw** [comment]
No worries! Should have thought about this first

**Comment by PeerHerholz** [comment]
Hi,

I'm closing this for now but please feel free to re-open if needed.

Cheers, Peer
