### ISSUE TITLE
Crazy dependencies

### ISSUE THREAD

**Issue by bthirion** [main-educational/brain_encoding_decoding#16]
Having to install pytorch and TF altogther is really too much. Actually, simple sklearn covers 90% of the cases.

**Comment by htwangtw** [comment]
Agreed, and every once in a while, i won't be able to build a environment. @srastegarnia the pytorch/TF requirement is related to your part, from what I remembered. Can you please look into simplifying for the tutorial?

**Comment by PeerHerholz** [comment]
Hi folks,

thx for bringing this up. I agree, it's quite a bit. I think it also came from the fact that until now the `decoding` and `encoding` part were combined. Thus, if we have everything together and tested, we should definitely evaluate and reduce the environment!

Thanks again, cheers, Peer

**Comment by bthirion** [comment]
All right. 
If it is of any help, the most problematic one to install is torch-sparse (pip install currently fails on my bow with a standard Ubuntu...)

**Comment by PeerHerholz** [comment]
Hi @bthirion,

 sorry to hear that you're having problems with the environment! I submitted a `PR` (#17) that should fix `library/version` related problems. At least it worked for me when creating a new environment with `python==3.8` and then running `pip install -r binder/requirements.txt`. Please let me know if I can be of help re this.

Best, Peer

**Comment by PeerHerholz** [comment]
Hi everyone,

as the dependency is more or less addressed, I'm going to close this `issue`. However, please feel free to reopen it if needed.

Cheers, Peer
