### ISSUE TITLE
'haxby_data' tutorial should introduce the NiftMasker

### ISSUE THREAD

**Issue by bthirion** [main-educational/brain_encoding_decoding#19]
Understanding `NiftiMasker` is always the hard part for people discovering nilearn.
In the 'haxby_data' tutorial it is very important that people understand how to go from images to ML kinds of objects

**Comment by PeerHerholz** [comment]
Hi @bthirion,

thanks for bringing this up.  Extracting signals from `MRI data`, ie `Maskers`, is covered in an earlier [tutorial](https://main-educational.github.io/intro_ML/functional-connectivity-with-nilearn.html#extracting-signal-from-fmri-volumes), specifically the [Machine learning in functional MRI using Nilearn](https://main-educational.github.io/intro_ML/index.html) session. Furthermore, almost every tutorial uses a different approach to get information from the images (some go from `image` to ML-ready data, while others e.g. compute a parcellation and subsequently connectivity between regions) and thus could/might/should address this correspondingly. However, we could add a little reminder of the different options to the `Haxby tutorial` if required. 

Best, Peer

**Comment by bthirion** [comment]
OK !

**Comment by PeerHerholz** [comment]
Hi,

I'm closing this for now but please feel free to re-open if needed!

Cheers, Peer
