### ISSUE TITLE
TensorFlow installation fails on M1 Mac

### ISSUE THREAD

**Issue by valosekj** [main-educational/brain_encoding_decoding#6]
I followed [setup for local installation](https://main-educational.github.io/brain_encoding_decoding/intro.html) and I got following error for `tensorflow`:

```
ERROR: Could not find a version that satisfies the requirement tensorflow==2.6.2 (from versions: none)
ERROR: No matching distribution found for tensorflow==2.6.2  
```

### Info about my system:
M1 MacBook with MacOS 11.6 (Big Sur)
Python 3.9.9
pip 21.3.1

### Steps to reproduce:

```
git clone https://github.com/main-educational/brain_encoding_decoding.git
cd brain_encoding_decoding
python3 -m venv env_tuto
source env_tuto/bin/activate
pip install -r binder/requirements.txt
``` 

### Full terminal output:

```
Collecting nilearn==0.8.0
  Using cached nilearn-0.8.0-py3-none-any.whl (4.9 MB)
Collecting psutil==5.8.0
  Using cached psutil-5.8.0.tar.gz (470 kB)
  Preparing metadata (setup.py) ... done
Collecting pandas==1.1.5
  Using cached pandas-1.1.5.tar.gz (5.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy==1.19.5
  Using cached numpy-1.19.5.zip (7.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting keras==2.6.0
  Using cached keras-2.6.0-py2.py3-none-any.whl (1.3 MB)
ERROR: Could not find a version that satisfies the requirement tensorflow==2.6.2 (from versions: none)
ERROR: No matching distribution found for tensorflow==2.6.2 
```

**Comment by pbellec** [comment]
Thanks for reporting!
Unfortunately I don't have a mac to test on my end.

Based on the [installation notes](https://www.tensorflow.org/install/pip#macos), it looks like tensorflow is supporting primarily Windows and Ubuntu.
Although there are references to Mac, it's not clear from their instructions how to proceed. 

This [blog post](https://developer.apple.com/forums/thread/683757) suggests to replace `tensorflow` by `tensorflow-macos` and `tensorflow-metal`.

I hope that's useful.

**Comment by valosekj** [comment]
I have probably found workaround using `miniforge`. 

1. Install `miniforge` from `brew`:

```
brew install miniforge
```

2. Modify your `.bashrc`/`.zshrc` file to point to the miniforge installed from brew:

```
# miniforge installed from brew
CONDA_PATH="/opt/homebrew/Caskroom/miniforge/base"
# Standard conda 
#CONDA_PATH="/Users/valosek/miniconda"
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('${CONDA_PATH}/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "${CONDA_PATH}/etc/profile.d/conda.sh" ]; then
        . "${CONDA_PATH}/etc/profile.d/conda.sh"
    else
        export PATH="${CONDA_PATH}/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
```

Save the `.bashrc`/`.zshrc` file and open new terminal.

3. Download [following config file](https://raw.githubusercontent.com/jeffheaton/t81_558_deep_learning/master/tensorflow-apple-metal.yml).

4. Create conda environment called `tensorflow`:

```
conda env create -n tensorflow --file tensorflow-apple-metal.yml
```

5. Activate the environment:

```
conda activate tensorflow 
```

6. Install some remaining packages:

```
conda install seaborn nilearn psutil scikit-learn matplotlib jupyter-book
```

Hope this will help some other future M1 users.

[Inspiration](https://github.com/jeffheaton/t81_558_deep_learning/blob/master/install/tensorflow-install-mac-metal-jul-2021.ipynb)

**Comment by pbellec** [comment]
Thanks a lot for sharing the detailed solution!
